-- Personalbudget: staff per scenario, calculated in the database and written to
-- the personnel accounts in budget_entries.
--
-- Design:
--   * ONE calculation — staff_cost_rows(). The staff view reads it, and
--     recalc_staff_budget() writes it to budget_entries. They cannot disagree.
--   * Recalculation runs in statement-level triggers, so every change to a person,
--     a period, an allocation or the parameters is in the budget as soon as the
--     write returns. A bulk import is one statement → one recalculation.
--   * The personnel accounts are locked: guard_staff_budget_entries() rejects any
--     write to them from the app. Only the recalculation (running as the function
--     owner) writes there.
--   * Visibility follows the existing scope rule via
--     user_can_access_company_cost_center(). A person is visible to anyone who can
--     see their home cost center or any cost center they are allocated to — and
--     those people may also change them (shared staff is editable by every
--     regional manager involved).
--
-- Foreign keys follow the FK delete rules decided 2026-09-16:
--   hand-entered data → NO ACTION against cost_centers, CASCADE from scenarios,
--   never SET NULL on scope columns, SET NULL on auth.users.
--
-- DDL only. Verification lives in verify_staff_budget.sql.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.staff_parameters (
  scenario_id                  integer PRIMARY KEY REFERENCES public.scenarios(id) ON DELETE CASCADE,
  salary_increase_pct          numeric NOT NULL DEFAULT 3,
  salary_increase_from         date,                         -- NULL = no increase in this scenario
  vacation_supplement_pct      numeric NOT NULL DEFAULT 0.8, -- % of monthly salary per vacation day
  vacation_supplement_month    smallint CHECK (vacation_supplement_month BETWEEN 1 AND 12), -- NULL = spread evenly
  employer_fee_pct             numeric NOT NULL DEFAULT 31.42,
  pension_pct                  numeric NOT NULL DEFAULT 8.5,
  payroll_tax_pct              numeric NOT NULL DEFAULT 24.26,
  absence_pct                  numeric NOT NULL DEFAULT 0,   -- reduces salary cost for sick leave, VAB etc.
  cost_sign                    smallint NOT NULL DEFAULT 1 CHECK (cost_sign IN (1, -1)),
  account_salary               text NOT NULL DEFAULT '7210',
  account_vacation_supplement  text DEFAULT '7285',
  account_employer_fee         text DEFAULT '7510',
  account_pension              text DEFAULT '7410',
  account_payroll_tax          text DEFAULT '7530',
  account_car_benefit          text DEFAULT '7390',
  account_car_benefit_fee      text DEFAULT '7510',
  book_car_benefit_value       boolean NOT NULL DEFAULT false, -- the benefit value itself is usually offset, only the fee is a cost
  default_salaries             jsonb NOT NULL DEFAULT '{}'::jsonb, -- { "<title>": <starting salary> } for recruitments
  -- Rollout switch. 'company_managers': only admins and the company's managers see
  -- and edit staff. 'everyone': anyone with scope on the person's cost centers.
  visibility                   text NOT NULL DEFAULT 'company_managers'
                               CHECK (visibility IN ('company_managers', 'everyone')),
  updated_by                   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at                   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.staff_members (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_id          integer NOT NULL REFERENCES public.scenarios(id) ON DELETE CASCADE,
  employee_no          text,
  first_name           text NOT NULL DEFAULT '',
  last_name            text NOT NULL DEFAULT '',
  title                text,
  employment_type      text CHECK (employment_type IN ('TV', 'PRO', 'TID')),
  is_recruitment       boolean NOT NULL DEFAULT false,
  home_cost_center_id  integer NOT NULL REFERENCES public.cost_centers(id) ON DELETE NO ACTION,
  included             boolean NOT NULL DEFAULT true,
  employment_rate      numeric NOT NULL DEFAULT 100 CHECK (employment_rate BETWEEN 0 AND 100),
  monthly_salary       numeric NOT NULL DEFAULT 0 CHECK (monthly_salary >= 0),
  supplement           numeric NOT NULL DEFAULT 0,
  vacation_days        smallint NOT NULL DEFAULT 25 CHECK (vacation_days BETWEEN 0 AND 60),
  car_benefit          numeric NOT NULL DEFAULT 0 CHECK (car_benefit >= 0), -- benefit value per year
  note                 text,
  reviewed_by          uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at          timestamptz,
  updated_by           uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (scenario_id, employee_no)
);
CREATE INDEX IF NOT EXISTS staff_members_scenario_idx ON public.staff_members (scenario_id);
CREATE INDEX IF NOT EXISTS staff_members_home_cc_idx  ON public.staff_members (home_cost_center_id);

-- Everything that varies during the year. Replaces the free-text comments and the
-- hand-edited month cells in the Excel file. Overlaps: the latest start wins.
CREATE TABLE IF NOT EXISTS public.staff_periods (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id    integer NOT NULL REFERENCES public.staff_members(id) ON DELETE CASCADE,
  from_period  date NOT NULL,  -- first day of the month
  to_period    date NOT NULL,  -- first day of the month, inclusive
  rate         numeric NOT NULL CHECK (rate BETWEEN 0 AND 100),
  reason       text,
  CHECK (to_period >= from_period)
);
CREATE INDEX IF NOT EXISTS staff_periods_member_idx ON public.staff_periods (member_id);

-- Salary split across cost centers. No rows = 100 % on the home cost center.
-- Shares are normalised in the calculation, so 17 + 11 + … need not hit exactly 100.
-- scenario_id is denormalised so the recalculation still knows the scenario when
-- a row disappears through a cascade from staff_members.
CREATE TABLE IF NOT EXISTS public.staff_allocations (
  member_id       integer NOT NULL REFERENCES public.staff_members(id) ON DELETE CASCADE,
  cost_center_id  integer NOT NULL REFERENCES public.cost_centers(id) ON DELETE NO ACTION,
  share           numeric NOT NULL CHECK (share >= 0),
  scenario_id     integer NOT NULL REFERENCES public.scenarios(id) ON DELETE CASCADE,
  PRIMARY KEY (member_id, cost_center_id)
);
CREATE INDEX IF NOT EXISTS staff_allocations_cc_idx ON public.staff_allocations (cost_center_id);

-- Rows written by the recalculation have no human author when it runs outside a
-- request (SQL editor). NULL is the honest value there.
ALTER TABLE public.budget_entries ALTER COLUMN updated_by DROP NOT NULL;

-- ---------------------------------------------------------------------------
-- Housekeeping triggers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.staff_allocations_set_scenario()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  SELECT m.scenario_id INTO NEW.scenario_id FROM staff_members m WHERE m.id = NEW.member_id;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS staff_allocations_set_scenario ON public.staff_allocations;
CREATE TRIGGER staff_allocations_set_scenario
  BEFORE INSERT OR UPDATE OF member_id ON public.staff_allocations
  FOR EACH ROW EXECUTE FUNCTION public.staff_allocations_set_scenario();

CREATE OR REPLACE FUNCTION public.staff_touch()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at := now();
  NEW.updated_by := COALESCE(auth.uid(), NEW.updated_by);
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS staff_members_touch ON public.staff_members;
CREATE TRIGGER staff_members_touch
  BEFORE INSERT OR UPDATE ON public.staff_members
  FOR EACH ROW EXECUTE FUNCTION public.staff_touch();

DROP TRIGGER IF EXISTS staff_parameters_touch ON public.staff_parameters;
CREATE TRIGGER staff_parameters_touch
  BEFORE INSERT OR UPDATE ON public.staff_parameters
  FOR EACH ROW EXECUTE FUNCTION public.staff_touch();

-- ---------------------------------------------------------------------------
-- The calculation — the only place the rules live
-- ---------------------------------------------------------------------------

-- One row per person, cost center and month, with every cost component.
-- SECURITY INVOKER: called from the app it only sees what RLS lets the user see;
-- called from recalc_staff_budget() it runs as the owner and sees everything.
CREATE OR REPLACE FUNCTION public.staff_cost_rows(
  p_scenario_id integer,
  p_cost_center_ids integer[] DEFAULT NULL
)
RETURNS TABLE (
  member_id            integer,
  cost_center_id       integer,
  year                 integer,
  month                integer,
  rate                 numeric,  -- effective employment rate that month, %
  share                numeric,  -- share of the person on this cost center, %
  salary               numeric,
  vacation_supplement  numeric,
  employer_fee         numeric,
  pension              numeric,
  payroll_tax          numeric,
  car_benefit          numeric,
  car_benefit_fee      numeric,
  total                numeric
)
LANGUAGE sql STABLE SET search_path = public AS $$
  WITH p AS (
    SELECT sp.*, s.start_year, s.start_month, s.end_year, s.end_month
    FROM staff_parameters sp
    JOIN scenarios s ON s.id = sp.scenario_id
    WHERE sp.scenario_id = p_scenario_id
  ),
  months AS (
    SELECT gs::date AS period
    FROM p, generate_series(
      make_date(p.start_year, p.start_month, 1),
      make_date(p.end_year, p.end_month, 1),
      interval '1 month'
    ) AS gs
  ),
  mem AS (
    SELECT m.* FROM staff_members m
    WHERE m.scenario_id = p_scenario_id AND m.included
  ),
  alloc AS (
    SELECT
      mem.id AS mid,
      COALESCE(a.cost_center_id, mem.home_cost_center_id) AS ccid,
      CASE
        WHEN a.member_id IS NULL THEN 1.0
        WHEN sum(a.share) OVER w > 0 THEN a.share / sum(a.share) OVER w
        ELSE 1.0 / count(*) OVER w
      END AS sh
    FROM mem
    LEFT JOIN staff_allocations a ON a.member_id = mem.id
    WINDOW w AS (PARTITION BY mem.id)
  ),
  monthly AS (
    SELECT
      al.mid, al.ccid, al.sh, mo.period,
      COALESCE(
        (SELECT pr.rate FROM staff_periods pr
          WHERE pr.member_id = mem.id AND mo.period BETWEEN pr.from_period AND pr.to_period
          ORDER BY pr.from_period DESC, pr.id DESC
          LIMIT 1),
        mem.employment_rate
      ) / 100.0 AS r,
      (mem.monthly_salary + mem.supplement)
        * CASE WHEN p.salary_increase_from IS NOT NULL AND mo.period >= p.salary_increase_from
               THEN 1 + p.salary_increase_pct / 100.0 ELSE 1 END AS full_salary,
      mem.vacation_days AS vdays,
      mem.car_benefit AS car_year
    FROM mem
    JOIN alloc al ON al.mid = mem.id
    CROSS JOIN months mo
    CROSS JOIN p
    WHERE p_cost_center_ids IS NULL OR al.ccid = ANY (p_cost_center_ids)
  ),
  amounts AS (
    SELECT
      m.*,
      m.full_salary * m.r * m.sh * (1 - p.absence_pct / 100.0) AS sal,
      m.full_salary * m.r * m.sh * p.vacation_supplement_pct / 100.0 * m.vdays / 12.0 AS vac_spread,
      m.car_year / 12.0 * m.sh AS car
    FROM monthly m CROSS JOIN p
  ),
  vac AS (
    SELECT
      a.*,
      CASE
        WHEN p.vacation_supplement_month IS NULL THEN a.vac_spread
        WHEN extract(month FROM a.period) = p.vacation_supplement_month
          THEN sum(a.vac_spread) OVER (PARTITION BY a.mid, a.ccid)
        ELSE 0
      END AS vac_amt
    FROM amounts a CROSS JOIN p
  ),
  parts AS (
    SELECT
      v.mid, v.ccid, v.period, v.r, v.sh,
      p.cost_sign * v.sal                                                          AS c_sal,
      p.cost_sign * v.vac_amt                                                      AS c_vac,
      p.cost_sign * (v.sal + v.vac_amt) * p.employer_fee_pct / 100.0               AS c_fee,
      p.cost_sign * (v.sal + v.vac_amt) * p.pension_pct / 100.0                    AS c_pen,
      p.cost_sign * (v.sal + v.vac_amt) * p.pension_pct / 100.0 * p.payroll_tax_pct / 100.0 AS c_tax,
      CASE WHEN p.book_car_benefit_value THEN p.cost_sign * v.car ELSE 0 END      AS c_car,
      p.cost_sign * v.car * p.employer_fee_pct / 100.0                             AS c_carfee
    FROM vac v CROSS JOIN p
  )
  SELECT
    x.mid, x.ccid,
    extract(year FROM x.period)::integer,
    extract(month FROM x.period)::integer,
    round(x.r * 100, 2), round(x.sh * 100, 2),
    x.c_sal, x.c_vac, x.c_fee, x.c_pen, x.c_tax, x.c_car, x.c_carfee,
    x.c_sal + x.c_vac + x.c_fee + x.c_pen + x.c_tax + x.c_car + x.c_carfee
  FROM parts x
$$;

-- Accounts the staff budget owns in a scenario. Empty when the scenario does
-- not use the staff budget (no staff_parameters row).
CREATE OR REPLACE FUNCTION public.staff_locked_account_ids(p_scenario_id integer)
RETURNS TABLE (account_id integer)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT a.id
  FROM staff_parameters sp
  JOIN scenarios s ON s.id = sp.scenario_id
  JOIN accounts a ON a.company_id = s.company_id
  WHERE sp.scenario_id = p_scenario_id
    AND a.account_number IN (
      sp.account_salary, sp.account_vacation_supplement, sp.account_employer_fee,
      sp.account_pension, sp.account_payroll_tax, sp.account_car_benefit,
      sp.account_car_benefit_fee
    )
$$;

-- Replaces the staff accounts' budget entries on the given cost centers (all
-- when NULL) with what the calculation says.
CREATE OR REPLACE FUNCTION public.recalc_staff_budget(
  p_scenario_id integer,
  p_cost_center_ids integer[] DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_company integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM staff_parameters WHERE scenario_id = p_scenario_id) THEN
    RETURN; -- staff budget not in use for this scenario
  END IF;
  SELECT company_id INTO v_company FROM scenarios WHERE id = p_scenario_id;

  DELETE FROM budget_entries be
  WHERE be.scenario_id = p_scenario_id
    AND be.account_id IN (SELECT l.account_id FROM staff_locked_account_ids(p_scenario_id) l)
    AND (p_cost_center_ids IS NULL OR be.cost_center_id = ANY (p_cost_center_ids));

  INSERT INTO budget_entries
    (scenario_id, account_id, cost_center_id, year, month, amount, counterpart_company_id, updated_by, updated_at)
  SELECT p_scenario_id, acc.id, r.cost_center_id, r.year, r.month,
         round(sum(c.amount)), NULL, auth.uid(), now()
  FROM staff_cost_rows(p_scenario_id, p_cost_center_ids) r
  CROSS JOIN staff_parameters sp
  CROSS JOIN LATERAL (VALUES
    (sp.account_salary,              r.salary),
    (sp.account_vacation_supplement, r.vacation_supplement),
    (sp.account_employer_fee,        r.employer_fee),
    (sp.account_pension,             r.pension),
    (sp.account_payroll_tax,         r.payroll_tax),
    (sp.account_car_benefit,         r.car_benefit),
    (sp.account_car_benefit_fee,     r.car_benefit_fee)
  ) AS c(account_number, amount)
  JOIN accounts acc ON acc.company_id = v_company AND acc.account_number = c.account_number
  WHERE sp.scenario_id = p_scenario_id AND c.account_number IS NOT NULL
  GROUP BY acc.id, r.cost_center_id, r.year, r.month
  HAVING round(sum(c.amount)) <> 0;
END $$;

REVOKE EXECUTE ON FUNCTION public.recalc_staff_budget(integer, integer[]) FROM PUBLIC, anon, authenticated;

-- Manual "recalculate everything" for admins.
CREATE OR REPLACE FUNCTION public.admin_recalc_staff_budget(p_scenario_id integer)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Only administrators can recalculate the staff budget' USING ERRCODE = '42501';
  END IF;
  PERFORM recalc_staff_budget(p_scenario_id, NULL);
END $$;

-- ---------------------------------------------------------------------------
-- Lock the staff accounts against hand edits
-- ---------------------------------------------------------------------------

-- SECURITY INVOKER on purpose: current_user is then the caller's role. The app
-- runs as authenticated; the recalculation runs as the function owner.
CREATE OR REPLACE FUNCTION public.guard_staff_budget_entries()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF current_user NOT IN ('authenticated', 'anon') THEN
    RETURN COALESCE(NEW, OLD);
  END IF;
  -- Nested IFs: SQL does not promise short-circuit evaluation, and NEW is NULL on DELETE.
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    IF EXISTS (
      SELECT 1 FROM staff_locked_account_ids(NEW.scenario_id) l WHERE l.account_id = NEW.account_id
    ) THEN
      RAISE EXCEPTION 'staff_locked_account: the account is calculated by the staff budget'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    IF EXISTS (
      SELECT 1 FROM staff_locked_account_ids(OLD.scenario_id) l WHERE l.account_id = OLD.account_id
    ) THEN
      RAISE EXCEPTION 'staff_locked_account: the account is calculated by the staff budget'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS guard_staff_budget_entries ON public.budget_entries;
CREATE TRIGGER guard_staff_budget_entries
  BEFORE INSERT OR UPDATE OR DELETE ON public.budget_entries
  FOR EACH ROW EXECUTE FUNCTION public.guard_staff_budget_entries();

-- ---------------------------------------------------------------------------
-- Recalculate on every change
-- ---------------------------------------------------------------------------
-- Statement-level with transition tables: an import of 300 people is one
-- recalculation, not 300. One trigger per event, because each needs its own
-- transition tables.

CREATE OR REPLACE FUNCTION public.staff_members_recalc()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    FOR r IN
      WITH changed AS (
        SELECT n.id, n.scenario_id, n.home_cost_center_id AS new_home, o.home_cost_center_id AS old_home
        FROM new_rows n JOIN old_rows o ON o.id = n.id
        WHERE (n.included, n.employment_rate, n.monthly_salary, n.supplement, n.vacation_days,
               n.car_benefit, n.home_cost_center_id, n.scenario_id)
          IS DISTINCT FROM
              (o.included, o.employment_rate, o.monthly_salary, o.supplement, o.vacation_days,
               o.car_benefit, o.home_cost_center_id, o.scenario_id)
      )
      SELECT x.scenario_id, array_agg(DISTINCT x.cc) AS ccs FROM (
        SELECT c.scenario_id, c.new_home AS cc FROM changed c
        UNION SELECT c.scenario_id, c.old_home FROM changed c
        UNION SELECT c.scenario_id, a.cost_center_id FROM changed c JOIN staff_allocations a ON a.member_id = c.id
      ) x GROUP BY x.scenario_id
    LOOP
      PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
    END LOOP;
  ELSIF TG_OP = 'INSERT' THEN
    FOR r IN
      SELECT n.scenario_id, array_agg(DISTINCT n.home_cost_center_id) AS ccs
      FROM new_rows n GROUP BY n.scenario_id
    LOOP
      PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
    END LOOP;
  ELSE
    -- Allocations are gone by now (cascade); their own trigger recalculates those cost centers.
    FOR r IN
      SELECT o.scenario_id, array_agg(DISTINCT o.home_cost_center_id) AS ccs
      FROM old_rows o GROUP BY o.scenario_id
    LOOP
      PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
    END LOOP;
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS staff_members_recalc_ins ON public.staff_members;
DROP TRIGGER IF EXISTS staff_members_recalc_upd ON public.staff_members;
DROP TRIGGER IF EXISTS staff_members_recalc_del ON public.staff_members;
CREATE TRIGGER staff_members_recalc_ins AFTER INSERT ON public.staff_members
  REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_members_recalc();
CREATE TRIGGER staff_members_recalc_upd AFTER UPDATE ON public.staff_members
  REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_members_recalc();
CREATE TRIGGER staff_members_recalc_del AFTER DELETE ON public.staff_members
  REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_members_recalc();

CREATE OR REPLACE FUNCTION public.staff_allocations_recalc()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT x.scenario_id, array_agg(DISTINCT x.cc) AS ccs FROM (
      -- home cost center too: it carries the person when the last allocation goes
      SELECT t.scenario_id, t.cost_center_id AS cc FROM (
        SELECT scenario_id, cost_center_id, member_id FROM new_rows WHERE TG_OP <> 'DELETE'
      ) t
      UNION SELECT m.scenario_id, m.home_cost_center_id FROM staff_members m
        WHERE TG_OP <> 'DELETE' AND m.id IN (SELECT member_id FROM new_rows)
    ) x GROUP BY x.scenario_id
  LOOP
    PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
  END LOOP;
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION public.staff_allocations_recalc_old()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT x.scenario_id, array_agg(DISTINCT x.cc) AS ccs FROM (
      SELECT o.scenario_id, o.cost_center_id AS cc FROM old_rows o
      UNION SELECT m.scenario_id, m.home_cost_center_id FROM staff_members m
        WHERE m.id IN (SELECT member_id FROM old_rows)
    ) x GROUP BY x.scenario_id
  LOOP
    PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
  END LOOP;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS staff_allocations_recalc_ins ON public.staff_allocations;
DROP TRIGGER IF EXISTS staff_allocations_recalc_upd_new ON public.staff_allocations;
DROP TRIGGER IF EXISTS staff_allocations_recalc_upd_old ON public.staff_allocations;
DROP TRIGGER IF EXISTS staff_allocations_recalc_del ON public.staff_allocations;
CREATE TRIGGER staff_allocations_recalc_ins AFTER INSERT ON public.staff_allocations
  REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_allocations_recalc();
-- An update can move a share from one cost center to another: recalc both sides.
CREATE TRIGGER staff_allocations_recalc_upd_new AFTER UPDATE ON public.staff_allocations
  REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_allocations_recalc();
CREATE TRIGGER staff_allocations_recalc_upd_old AFTER UPDATE ON public.staff_allocations
  REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_allocations_recalc_old();
CREATE TRIGGER staff_allocations_recalc_del AFTER DELETE ON public.staff_allocations
  REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_allocations_recalc_old();

CREATE OR REPLACE FUNCTION public.staff_periods_recalc()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
BEGIN
  FOR r IN
    WITH touched AS (
      SELECT member_id FROM new_rows WHERE TG_OP <> 'DELETE'
    )
    SELECT x.scenario_id, array_agg(DISTINCT x.cc) AS ccs FROM (
      SELECT m.scenario_id, m.home_cost_center_id AS cc FROM staff_members m WHERE m.id IN (SELECT member_id FROM touched)
      UNION SELECT a.scenario_id, a.cost_center_id FROM staff_allocations a WHERE a.member_id IN (SELECT member_id FROM touched)
    ) x GROUP BY x.scenario_id
  LOOP
    PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
  END LOOP;
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION public.staff_periods_recalc_old()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r record;
BEGIN
  -- A member deleted in the same statement no longer resolves; the member's own trigger covers it.
  FOR r IN
    SELECT x.scenario_id, array_agg(DISTINCT x.cc) AS ccs FROM (
      SELECT m.scenario_id, m.home_cost_center_id AS cc FROM staff_members m WHERE m.id IN (SELECT member_id FROM old_rows)
      UNION SELECT a.scenario_id, a.cost_center_id FROM staff_allocations a WHERE a.member_id IN (SELECT member_id FROM old_rows)
    ) x GROUP BY x.scenario_id
  LOOP
    PERFORM recalc_staff_budget(r.scenario_id, r.ccs);
  END LOOP;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS staff_periods_recalc_ins ON public.staff_periods;
DROP TRIGGER IF EXISTS staff_periods_recalc_upd ON public.staff_periods;
DROP TRIGGER IF EXISTS staff_periods_recalc_del ON public.staff_periods;
CREATE TRIGGER staff_periods_recalc_ins AFTER INSERT ON public.staff_periods
  REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_periods_recalc();
CREATE TRIGGER staff_periods_recalc_upd AFTER UPDATE ON public.staff_periods
  REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_periods_recalc();
CREATE TRIGGER staff_periods_recalc_del AFTER DELETE ON public.staff_periods
  REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION public.staff_periods_recalc_old();

-- Parameters: turning the staff budget on, or changing a rate, recalculates the
-- whole scenario. Changing an account number first clears the old account, which
-- would otherwise keep stale amounts that nobody can edit any more.
CREATE OR REPLACE FUNCTION public.staff_parameters_recalc()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_company integer;
BEGIN
  IF TG_OP = 'DELETE' THEN
    RETURN NULL; -- turning it off keeps the amounts as ordinary, editable entries
  END IF;
  IF TG_OP = 'UPDATE' THEN
    SELECT company_id INTO v_company FROM scenarios WHERE id = OLD.scenario_id;
    DELETE FROM budget_entries be
    USING accounts a
    WHERE be.scenario_id = OLD.scenario_id
      AND a.id = be.account_id
      AND a.company_id = v_company
      AND a.account_number IN (
        OLD.account_salary, OLD.account_vacation_supplement, OLD.account_employer_fee,
        OLD.account_pension, OLD.account_payroll_tax, OLD.account_car_benefit,
        OLD.account_car_benefit_fee
      );
  END IF;
  PERFORM recalc_staff_budget(NEW.scenario_id, NULL);
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS staff_parameters_recalc ON public.staff_parameters;
CREATE TRIGGER staff_parameters_recalc
  AFTER INSERT OR UPDATE OR DELETE ON public.staff_parameters
  FOR EACH ROW EXECUTE FUNCTION public.staff_parameters_recalc();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

-- Company managers of the scenario's company (a NULL company_id on the role means
-- every company, same as in the other policies).
CREATE OR REPLACE FUNCTION public.user_is_company_manager_for(p_company_id integer)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM user_roles ur
    WHERE ur.user_id = auth.uid()
      AND ur.role = 'company_manager'
      AND (ur.company_id IS NULL OR ur.company_id = p_company_id)
  )
$$;

-- Who may see and change a person.
--   visibility = 'company_managers' (the default while rolling out): admins and the
--     company's managers only.
--   visibility = 'everyone': also anyone who can see the person's home cost center
--     or any cost center they are allocated to.
-- SECURITY DEFINER so the lookups are not themselves filtered by RLS (circular).
CREATE OR REPLACE FUNCTION public.user_can_access_staff(
  p_scenario_id integer,
  p_home_cost_center_id integer,
  p_member_id integer
)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT is_admin() OR EXISTS (
    SELECT 1 FROM scenarios s
    JOIN staff_parameters sp ON sp.scenario_id = s.id
    WHERE s.id = p_scenario_id
      AND (
        user_is_company_manager_for(s.company_id)
        OR (
          sp.visibility = 'everyone'
          AND (
            user_can_access_company_cost_center(s.company_id, p_home_cost_center_id)
            OR EXISTS (
              SELECT 1 FROM staff_allocations a
              WHERE a.member_id = p_member_id
                AND user_can_access_company_cost_center(s.company_id, a.cost_center_id)
            )
          )
        )
      )
  )
$$;

CREATE OR REPLACE FUNCTION public.user_can_access_staff_member(p_member_id integer)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    (SELECT user_can_access_staff(m.scenario_id, m.home_cost_center_id, m.id)
     FROM staff_members m WHERE m.id = p_member_id),
    false
  )
$$;

ALTER TABLE public.staff_parameters  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_members     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_periods     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_allocations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS staff_parameters_select ON public.staff_parameters;
DROP POLICY IF EXISTS staff_parameters_admin  ON public.staff_parameters;
CREATE POLICY staff_parameters_select ON public.staff_parameters
  FOR SELECT TO authenticated USING (true);
CREATE POLICY staff_parameters_admin ON public.staff_parameters
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

DROP POLICY IF EXISTS staff_members_select ON public.staff_members;
DROP POLICY IF EXISTS staff_members_insert ON public.staff_members;
DROP POLICY IF EXISTS staff_members_update ON public.staff_members;
DROP POLICY IF EXISTS staff_members_delete ON public.staff_members;
CREATE POLICY staff_members_select ON public.staff_members
  FOR SELECT TO authenticated
  USING (user_can_access_staff(scenario_id, home_cost_center_id, id));
CREATE POLICY staff_members_insert ON public.staff_members
  FOR INSERT TO authenticated
  WITH CHECK (user_can_access_staff(scenario_id, home_cost_center_id, id));
-- Both USING and WITH CHECK — an UPDATE policy without WITH CHECK rejects the new row silently.
CREATE POLICY staff_members_update ON public.staff_members
  FOR UPDATE TO authenticated
  USING (user_can_access_staff(scenario_id, home_cost_center_id, id))
  WITH CHECK (user_can_access_staff(scenario_id, home_cost_center_id, id));
CREATE POLICY staff_members_delete ON public.staff_members
  FOR DELETE TO authenticated
  USING (user_can_access_staff(scenario_id, home_cost_center_id, id));

DROP POLICY IF EXISTS staff_periods_all ON public.staff_periods;
CREATE POLICY staff_periods_all ON public.staff_periods
  FOR ALL TO authenticated
  USING (user_can_access_staff_member(member_id))
  WITH CHECK (user_can_access_staff_member(member_id));

DROP POLICY IF EXISTS staff_allocations_all ON public.staff_allocations;
CREATE POLICY staff_allocations_all ON public.staff_allocations
  FOR ALL TO authenticated
  USING (user_can_access_staff_member(member_id))
  WITH CHECK (user_can_access_staff_member(member_id));
